name: CI Pipeline/Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ci-build-and-push-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_IMAGE: $DOCKERHUB_USERNAME/bill-reminder-app:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to dockerhub
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - name: Build docker image
        run: docker build -t $DOCKER_IMAGE .
      - name: Push docker image to dockerhub
        run: docker push $DOCKER_IMAGE